### PR TITLE
Integrate conceptual model

### PR DESCRIPTION
**Pull request by mdasifhasan**

### CODE REVIEW

**Comment by mmaroti** [comment]
I have discussed it with Brian, and we think that snap-physics should not be modified. Can you move your snap.html to the c2stem-main project?

**Comment by mdasifhasan** [comment]
Please merge this branch with the master branch.

**Comment by mmaroti** [comment]
Asif, please update your submodules so it matches the one in master, after that I will merge

**Comment by mdasifhasan** [comment]
The conceptual model looks stable now. You may merge it.

**Pull request merged**
